# custom image
# image: axonasif/workspace-python@sha256:f5ba627a31505ea6cf100abe8e552d7ff9e0abd6ba46745b6d6dab349c001430

tasks:
  - name: Setup Okteto and kubectl
    command: bash $GITPOD_REPO_ROOT/gitpod/install-setup-okteto.sh

# ports:
#   - port: 5000
#     onOpen: ignore

vscode:
  extensions:
    - ms-python.python
